CREATE SEQUENCE SEQ_QUALIDADE_AR
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE tbl_qualidade_ar (
    USUARIO_ID INTEGER DEFAULT SEQ_QUALIDADE_AR NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(20) NOT NULL
);